openapi: 3.2.0
info:
  title: TDP Plg Auth Check API
  description: TANF Data Portal API documentation
  contact:
    email: tanfdata@acf.hhs.gov
  version: v1
servers:
- url: https://tanfdata.acf.hhs.gov/
security:
- Basic: []
tags:
- name: plg_auth_check
paths:
  /plg_auth_check/:
    parameters: []
    get:
      operationId: plg_auth_check_list
      description: Handle get request and verify user is authorized to access plg apps.
      responses:
        '200':
          description: ''
      tags:
      - plg_auth_check
      summary: Plg auth check list
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
